### ISSUE TITLE
Missing MapAndreas_GetAddress

### ISSUE THREAD

**Issue by Misiur** [Sphinxila/samp-plugin-mapandreas#1]
Hi, I think there's `MapAndreas_GetAddress` function missing (at least from `.inc` file). Could you add that?

**Comment by Sphinxila** [comment]
This plugin is kinda outdated.
This seems to be a good alternative:
- http://forum.sa-mp.com/showthread.php?t=586068

- https://github.com/Sphinxila/samp-plugin-mapandreas/blob/master/include/mapandreas.inc
There is no implementation for MapAndreas_GetAddress.
I think you wana get the pointer of the heightmap right?

Pull requests are welcome.
